### PR TITLE
Support custom load point, recognize nop and align padding

### PR DESCRIPTION
**Pull request by PikalaxALT**

### CODE REVIEW

**Comment by camthesaxman** [comment]
What ROMs are good test cases for this? Specifically ones that caused trouble when disassembling

**Comment by jiangzhengwenjz** [comment]
For my part, 
[`19755c3`](https://github.com/camthesaxman/gbadisasm/pull/3/commits/19755c3832406143986aae062424f7282bd06c91) fixes `b4bd50e4131b027c334547b4524e2dbbd4227130`  BZME.gba (The Legend of Zelda: The Minish Cap)
Other modifications are all for `274b102b6d940f46861a92b4e65f89a51815c12c`  B8KE.gba (Kirby & the Amazing Mirror) 
It passes an extra test case: `d7cf8f156ba9c455d164e1ea780a6bf1945465c2`  BPEJ.gba (Pokemon Emerald JP)

(sha1)

**Comment by camthesaxman** [comment]
Do you have any config files set up for those?

**Comment by jiangzhengwenjz** [comment]
@camthesaxman 
I lost my BZME.cfg since it's months ago. 
for B8KE: [B8KE.cfg](https://gist.github.com/jiangzhengwenjz/cb75b80929ae1de8154a8f7a7a4c7409)
for emerald jp I directly downloaded from [here](https://github.com/pret/pokeemerald-jp/blob/master/pokeemerald_jp.cfg)

**Pull request merged**
